name: Build and Test AUR Package

on:
  push:
    branches:
      - main  # Adjust this if your main branch is named differently
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Calculate SHA-256 checksum
        run: |
          cd ${{ github.workspace }}
          wget https://github.com/pop-os/gui-scale-applet/archive/v2.0.0.tar.gz -O gui-scale-applet-2.0.0.tar.gz
          sha256sum gui-scale-applet-2.0.0.tar.gz
        shell: bash
