name: Build and Test AUR Package

on:
  push:
    branches:
      - main  # Adjust this if your main branch is named differently
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest[_{{{CITATION{{{_2{archlinux-docker/README.md at master - GitHub](https://github.com/archlinux/archlinux-docker/blob/master/README.md)[_{{{CITATION{{{_2{archlinux-docker/README.md at master - GitHub](https://github.com/archlinux/archlinux-docker/blob/master/README.md)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build AUR Package
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest /bin/bash -c "
          pacman -Sy --noconfirm base-devel fakeroot
          cd path/to/your/PKGBUILD
          makepkg -si --noconfirm"[_{{{CITATION{{{_3{GitHub - archlinux/archlinux-docker: Docker Base Image for Arch Linux ...](https://github.com/archlinux/archlinux-docker)
      
      - name: Test AUR Package
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest /bin/bash -c "
          cd path/to/your/PKGBUILD
          makepkg --noconfirm"[_{{{CITATION{{{_3{GitHub - archlinux/archlinux-docker: Docker Base Image for Arch Linux ...](https://github.com/archlinux/archlinux-docker)
```[_{{{CITATION{{{_3{GitHub - archlinux/archlinux-docker: Docker Base Image for Arch Linux ...](https://github.com/archlinux/archlinux-docker)

This should resolve the image retrieval issue[_{{{CITATION{{{_3{GitHub - archlinux/archlinux-docker: Docker Base Image for Arch Linux ...](https://github.com/archlinux/archlinux-docker). Give it a try and let me know how it goes! If you face any other issues, let’s work through them together. 😊
