name: Build and Test AUR Package

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Prepare Build Environment
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:base-devel /bin/bash -c '
            pacman -Sy --noconfirm fakeroot wget sudo && \
            useradd -m -r aurbuilder && \
            mkdir -p /etc/sudoers.d && \
            echo "aurbuilder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/aurbuilder'
        shell: bash

      - name: Build AUR Package
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:base-devel /bin/bash -c '
            chown -R aurbuilder:aurbuilder /workspace && \
            sudo -u aurbuilder bash -c "makepkg -si --noconfirm"'
        shell: bash