name: Build and Test AUR Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build AUR Package
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:base-devel /bin/bash -c "
          pacman -Sy --noconfirm fakeroot wget sudo
          useradd -m -r aurbuilder
          mkdir -p /etc/sudoers.d
          echo 'aurbuilder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/aurbuilder
          chown -R aurbuilder /workspace
          sudo -u aurbuilder bash -c 'cd /workspace && mkdir -p build && cd build && wget https://github.com/cosmic-utils/gui-scale-applet/archive/refs/tags/2.0.0.tar.gz -O gui-scale-applet-2.0.0.tar.gz && sha256sum gui-scale-applet-2.0.0.tar.gz'
          sudo -u aurbuilder bash -c 'cd /workspace/build && makepkg -si --noconfirm'"
      
      - name: Test AUR Package
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:base-devel /bin/bash -c "
          sudo -u aurbuilder bash -c 'cd /workspace/build && makepkg --noconfirm'"
