name: Build and Test AUR Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build AUR Package
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest /bin/bash -c "
          pacman -Sy --noconfirm base-devel fakeroot sudo wget
          useradd -m -r aurbuilder
          chown -R aurbuilder:aurbuilder /workspace
          echo 'aurbuilder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/aurbuilder
          sudo -u aurbuilder wget https://github.com/cosmic-utils/gui-scale-applet/archive/refs/tags/2.0.0.tar.gz -O /workspace/gui-scale-applet-2.0.0.tar.gz
          sudo -u aurbuilder sha256sum /workspace/gui-scale-applet-2.0.0.tar.gz
          sudo -u aurbuilder bash -c 'cd /workspace && makepkg -si --noconfirm'"
      
      - name: Test AUR Package
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest /bin/bash -c "
          chown -R aurbuilder:aurbuilder /workspace
          echo 'aurbuilder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/aurbuilder
          sudo -u aurbuilder bash -c 'cd /workspace && makepkg --noconfirm'"
