name: Build and Test AUR Package

on:
  push:
    branches:
      - main  # Adjust this if your main branch is named differently
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build AUR Package
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest /bin/bash -c "
          pacman -Sy --noconfirm base-devel fakeroot
          cd path/to/your/PKGBUILD
          makepkg -si --noconfirm"
      
      - name: Test AUR Package
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest /bin/bash -c "
          cd path/to/your/PKGBUILD
          makepkg --noconfirm"
